# Generated by Django 6.0.2 on 2026-02-16 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='print_files/')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printing', 'Printing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('printer_name', models.CharField(default='HP LaserJet Pro 4004d', max_length=255)),
                ('copies', models.IntegerField(default=1)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Print History',
                'verbose_name_plural': 'Print Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
